export const workerCategories = {
  categories: [
    {
      id: 1,
      Worker_Role: "Astrologer",
      icon: "https://example.com/icons/astrologer.png",
    },
    {
      id: 2,
      Worker_Role: "Makeup Artist",
      icon: "https://example.com/icons/makeup_artist.png",
    },
    {
      id: 3,
      Worker_Role: "Photographer",
      icon: "https://example.com/icons/photographer.png",
    },
    {
      id: 4,
      Worker_Role: "Mehndi Artist",
      icon: "https://example.com/icons/mehndi_artist.png",
    },
    {
      id: 5,
      Worker_Role: "Assistant",
      icon: "https://example.com/icons/assistant.png",
    },
  ],
};

export const workerProfiles = {
  workers: [
    {
      id: 1,
      name: "John Doe",
      country: "USA",
      countryFlag: "🇺🇸",
      profileImage: "https://i.pravatar.cc/300",
      role: "Astrologer",
    },
    {
      id: 2,
      name: "Jane Smith",
      country: "India",
      countryFlag: "🇮🇳",
      profileImage: "https://i.pravatar.cc/300",
      role: "Makeup Artist",
    },
    {
      id: 3,
      name: "Ali Khan",
      country: "Pakistan",
      countryFlag: "🇵🇰",
      profileImage: "https://i.pravatar.cc/300",
      role: "Photographer",
    },
    {
      id: 4,
      name: "Maria Garcia",
      country: "Spain",
      countryFlag: "🇪🇸",
      profileImage: "https://i.pravatar.cc/300",
      role: "Mehndi Artist",
    },
    {
      id: 5,
      name: "Liu Wei",
      country: "China",
      countryFlag: "🇨🇳",
      profileImage: "https://i.pravatar.cc/300",
      role: "Assistant",
    },
    {
      id: 6,
      name: "Olga Ivanova",
      country: "Russia",
      countryFlag: "🇷🇺",
      profileImage: "https://i.pravatar.cc/300",
      role: "Astrologer",
    },
    {
      id: 7,
      name: "Carlos Hernandez",
      country: "Mexico",
      countryFlag: "🇲🇽",
      profileImage: "https://i.pravatar.cc/300",
      role: "Makeup Artist",
    },
    {
      id: 8,
      name: "Yuki Tanaka",
      country: "Japan",
      countryFlag: "🇯🇵",
      profileImage: "https://i.pravatar.cc/300",
      role: "Photographer",
    },
    {
      id: 9,
      name: "Fatima Ahmed",
      country: "Egypt",
      countryFlag: "🇪🇬",
      profileImage: "https://i.pravatar.cc/300",
      role: "Mehndi Artist",
    },
    {
      id: 10,
      name: "Victor Leblanc",
      country: "France",
      countryFlag: "🇫🇷",
      profileImage: "https://i.pravatar.cc/300",
      role: "Assistant",
    },
    {
      id: 11,
      name: "Aisha Mohammed",
      country: "Nigeria",
      countryFlag: "🇳🇬",
      profileImage: "https://i.pravatar.cc/300",
      role: "Astrologer",
    },
    {
      id: 12,
      name: "Lara Schmidt",
      country: "Germany",
      countryFlag: "🇩🇪",
      profileImage: "https://i.pravatar.cc/300",
      role: "Makeup Artist",
    },
    {
      id: 13,
      name: "Pedro Alves",
      country: "Brazil",
      countryFlag: "🇧🇷",
      profileImage: "https://i.pravatar.cc/300",
      role: "Photographer",
    },
    {
      id: 14,
      name: "Sophia Rossi",
      country: "Italy",
      countryFlag: "🇮🇹",
      profileImage: "https://i.pravatar.cc/300",
      role: "Mehndi Artist",
    },
    {
      id: 15,
      name: "Abdullah Yildirim",
      country: "Turkey",
      countryFlag: "🇹🇷",
      profileImage: "https://i.pravatar.cc/300",
      role: "Assistant",
    },
    {
      id: 16,
      name: "Grace Thompson",
      country: "Canada",
      countryFlag: "🇨🇦",
      profileImage: "https://i.pravatar.cc/300",
      role: "Astrologer",
    },
    {
      id: 17,
      name: "Ming Zhao",
      country: "China",
      countryFlag: "🇨🇳",
      profileImage: "https://i.pravatar.cc/300",
      role: "Makeup Artist",
    },
    {
      id: 18,
      name: "Ravi Patel",
      country: "India",
      countryFlag: "🇮🇳",
      profileImage: "https://i.pravatar.cc/300",
      role: "Photographer",
    },
    {
      id: 19,
      name: "Sofia Gonzalez",
      country: "Argentina",
      countryFlag: "🇦🇷",
      profileImage: "https://i.pravatar.cc/300",
      role: "Mehndi Artist",
    },
    {
      id: 20,
      name: "Mohamed Hassan",
      country: "Egypt",
      countryFlag: "🇪🇬",
      profileImage: "https://i.pravatar.cc/300",
      role: "Assistant",
    },
  ],
};
